default_platform(:ios)

platform :ios do
  desc "Build and Deploy (Generic)"
  lane :deploy do |options|
    flavor = options[:flavor] || "dev"
    # Scheme matching: HelpingHand (prod), HelpingHand Stg (stg), HelpingHand Dev (dev)
    # Adjust schema names based on flavorizr output
    scheme = "HelpingHand"
    if flavor == "dev"
      scheme = "HelpingHand Dev"
    elsif flavor == "stg"
      scheme = "HelpingHand Stg"
    end

    # match(type: "appstore")
    
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: scheme)
    
    # upload_to_testflight
  end
end
